In [1]:
import numpy as np
import pandas as pd
from pprint import pprint

In [2]:
def add_n(a,b,c):
    """ add three numbers """
    return a + b + c


In [3]:
add_n?

In [4]:
a1 = np.random.randn(3,3)
a1

array([[-0.99371189,  0.05992785,  0.68569312],
       [ 1.19996665,  0.18747378,  0.79857071],
       [-0.68591499, -0.13808121,  0.99590828]])

In [5]:
pprint(a1)

array([[-0.99371189,  0.05992785,  0.68569312],
       [ 1.19996665,  0.18747378,  0.79857071],
       [-0.68591499, -0.13808121,  0.99590828]])


In [6]:
a1.dtype

dtype('float64')

In [7]:
a1.shape

(3, 3)

In [8]:
a2 = [[1,2,3,4], [5,6,7,8]]
a2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [9]:
b2 = np.array(a2)
b2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
b2.shape

(2, 4)

In [11]:
b2.dtype

dtype('int32')

## Pandas DataFrame

In [12]:
data = { 
    'State' : ['NY','CHI','TX','AL','CZ',],
    'Name' : ['Park','Lee','Oh','Choi','Jeong',],
    'Value' : [12.1, 4.5, 6.6, 78.1, 44.2],
    'Comments' : ['-','-','-','-','-',],
    'Remark' : ['Good','Normal','Normal','Bad','Bad',],
}

data

{'State': ['NY', 'CHI', 'TX', 'AL', 'CZ'],
 'Name': ['Park', 'Lee', 'Oh', 'Choi', 'Jeong'],
 'Value': [12.1, 4.5, 6.6, 78.1, 44.2],
 'Comments': ['-', '-', '-', '-', '-'],
 'Remark': ['Good', 'Normal', 'Normal', 'Bad', 'Bad']}

In [13]:
pprint(data)

{'Comments': ['-', '-', '-', '-', '-'],
 'Name': ['Park', 'Lee', 'Oh', 'Choi', 'Jeong'],
 'Remark': ['Good', 'Normal', 'Normal', 'Bad', 'Bad'],
 'State': ['NY', 'CHI', 'TX', 'AL', 'CZ'],
 'Value': [12.1, 4.5, 6.6, 78.1, 44.2]}


In [14]:
df1 = pd.DataFrame(data)
df1

State   Name  Value Comments  Remark
0    NY   Park   12.1        -    Good
1   CHI    Lee    4.5        -  Normal
2    TX     Oh    6.6        -  Normal
3    AL   Choi   78.1        -     Bad
4    CZ  Jeong   44.2        -     Bad

In [15]:
df2 = pd.DataFrame(data, columns=['Name','State','Value','Remark','Comments',])
df2

Name State  Value  Remark Comments
0   Park    NY   12.1    Good        -
1    Lee   CHI    4.5  Normal        -
2     Oh    TX    6.6  Normal        -
3   Choi    AL   78.1     Bad        -
4  Jeong    CZ   44.2     Bad        -

In [16]:
df2?

In [17]:
df3 = pd.DataFrame(data, 
                   columns=['Name','State','Value','Remark','Comments',],
                   index= ['one','two','three','four','five'],                  
                  )
df3

Name State  Value  Remark Comments
one     Park    NY   12.1    Good        -
two      Lee   CHI    4.5  Normal        -
three     Oh    TX    6.6  Normal        -
four    Choi    AL   78.1     Bad        -
five   Jeong    CZ   44.2     Bad        -

In [21]:
df4 = pd.DataFrame(data, 
                   columns=['Name','State','Value','Remark','Comments',],
                   index=None,                  
                  )
df4

Name State  Value  Remark Comments
0   Park    NY   12.1    Good        -
1    Lee   CHI    4.5  Normal        -
2     Oh    TX    6.6  Normal        -
3   Choi    AL   78.1     Bad        -
4  Jeong    CZ   44.2     Bad        -